POST http://localhost:3000/user/singup
Content-Type: application/json

{
    "name": "desafiosharenergy",
    "email": "desafiosharenergy@gmail.com",
    "password": "sh@r3n3rgy"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "desafiosharenergy",
    "password": "sh@r3n3rgy"
}